services:
  - type: web
    name: broker-hub-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CASHFREE_API_KEY
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
    healthCheckPath: /api/test
    autoDeploy: true
    buildFilter:
      paths:
        - prisma/**
        - src/**
        - package.json 